data_format: colmap  # colmap or blender
white_background: false
dataloader_workers: 2
device: cuda:0
random_seed: 0
log_every: 200

# true: the train dataset does not contain the eval dataset
# false: all the data is used for training
eval: true
eval_split_ratio: 0.125  # only used when data_format is colmap
eval_in_val: false  # only used when data_format is blender
eval_in_test: false  # only used when data_format is blender
eval_every: 2000
eval_render_num: 3

total_iterations: 30000
save_model_iterations: [30000]

sh_degree: 3
sh_degree_interval: 2000

use_masks: false

means_lr_init: 0.001
means_lr_final: 0.000001
means_lr_schedule_max_steps: 25000
log_scales_lr: 0.001
quats_lr: 0.001
sh_0_lr: 0.0025
sh_rest_lr: 0.000125
logit_opacities_lr: 0.05

refine_start: 1000
refine_stop: 25000
refine_every: 150
reset_opacities_every: 2000
min_opacity: 0.005
densify_grad_thresh: 0.0005
densify_scale_thresh: 0.06
num_splits: 2
prune_radii_ratio_thresh: 0.15
prune_scale_thresh: 1.0

lambda_ssim: 0.2

use_scale_regularization: false
max_scale_ratio: 10.0
lambda_scale: 0.1

